version: "3.3"

services: 
  app:
    container_name: raj_upwork_v2
    restart: always 
    build: .
    networks:
      - kong-net
    ports:
      - "7002:6500"

networks:
  kong-net:
    driver: bridge
    ipam: 
      driver: default 








