package all

import (
	"strconv"

	models "github.com/Aphofisis/raj_upwork_v2/models"
)

func Si_Find_Annual(symbol string, limit int) ([]models.FinancialRatio_Annual, error) {

	db := models.SingleStoreCN
	q := `SELECT date,
    symbol,
    period,
    currentRatio,
    quickRatio,
    cashRatio,
    daysOfSalesOutstanding,
    daysOfInventoryOutstanding,
    operatingCycle,
    daysOfPayablesOutstanding,
    cashConversionCycle,
    grossProfitMargin,
    operatingProfitMargin,
    pretaxProfitMargin,
    netProfitMargin,
    effectiveTaxRate,
    returnOnAssets,
    returnOnEquity,
    returnOnCapitalEmployed,
    netIncomePerEBT,
    ebtPerEbit,
    ebitPerRevenue,
    debtRatio,
    debtEquityRatio,
    longTermDebtToCapitalization,
    totalDebtToCapitalization,
    interestCoverage,
    cashFlowToDebtRatio,
    companyEquityMultiplier,
    receivablesTurnover,
    payablesTurnover,
    inventoryTurnover,
    fixedAssetTurnover,
    assetTurnover,
    operatingCashFlowPerShare,
    freeCashFlowPerShare,
    cashPerShare,
    payoutRatio,
    operatingCashFlowSalesRatio,
    freeCashFlowOperatingCashFlowRatio,
    cashFlowCoverageRatios,
    shortTermCoverageRatios,
    capitalExpenditureCoverageRatio,
    dividendPaidAndCapexCoverageRatio,
    dividendPayoutRatio,
    priceBookValueRatio,
    priceToBookRatio,
    priceEarningsRatio,
    priceToFreeCashFlowsRatio,
    priceToOperatingCashFlowsRatio,
    priceCashFlowRatio,
    priceEarningsToGrowthRatio,
    priceSalesRatio,
    dividendYield,
    enterpriseValueMultiple,
    priceFairValue FROM FinancialRatio_Annual WHERE symbol = ? LIMIT ` + strconv.Itoa(limit)
	rows, error_show := db.Query(q, symbol)

	oListFRA := []models.FinancialRatio_Annual{}

	if error_show != nil {

		return oListFRA, error_show
	}

	for rows.Next() {
		oFRA := models.FinancialRatio_Annual{}
		rows.Scan(&oFRA.Date,
			&oFRA.Symbol,
			&oFRA.Period,
			&oFRA.CurrentRatio,
			&oFRA.QuickRatio,
			&oFRA.CashRatio,
			&oFRA.DaysOfSalesOutstanding,
			&oFRA.DaysOfInventoryOutstanding,
			&oFRA.OperatingCycle,
			&oFRA.DaysOfPayablesOutstanding,
			&oFRA.CashConversionCycle,
			&oFRA.GrossProfitMargin,
			&oFRA.OperatingProfitMargin,
			&oFRA.PretaxProfitMargin,
			&oFRA.NetProfitMargin,
			&oFRA.EffectiveTaxRate,
			&oFRA.ReturnOnAssets,
			&oFRA.ReturnOnEquity,
			&oFRA.ReturnOnCapitalEmployed,
			&oFRA.NetIncomePerEBT,
			&oFRA.EbtPerEbit,
			&oFRA.EbitPerRevenue,
			&oFRA.DebtRatio,
			&oFRA.DebtEquityRatio,
			&oFRA.LongTermDebtToCapitalization,
			&oFRA.TotalDebtToCapitalization,
			&oFRA.InterestCoverage,
			&oFRA.CashFlowToDebtRatio,
			&oFRA.CompanyEquityMultiplier,
			&oFRA.ReceivablesTurnover,
			&oFRA.PayablesTurnover,
			&oFRA.InventoryTurnover,
			&oFRA.FixedAssetTurnover,
			&oFRA.AssetTurnover,
			&oFRA.OperatingCashFlowPerShare,
			&oFRA.FreeCashFlowPerShare,
			&oFRA.CashPerShare,
			&oFRA.PayoutRatio,
			&oFRA.OperatingCashFlowSalesRatio,
			&oFRA.FreeCashFlowOperatingCashFlowRatio,
			&oFRA.CashFlowCoverageRatios,
			&oFRA.ShortTermCoverageRatios,
			&oFRA.CapitalExpenditureCoverageRatio,
			&oFRA.DividendPaidAndCapexCoverageRatio,
			&oFRA.DividendPayoutRatio,
			&oFRA.PriceBookValueRatio,
			&oFRA.PriceToBookRatio,
			&oFRA.PriceEarningsRatio,
			&oFRA.PriceToFreeCashFlowsRatio,
			&oFRA.PriceToOperatingCashFlowsRatio,
			&oFRA.PriceCashFlowRatio,
			&oFRA.PriceEarningsToGrowthRatio,
			&oFRA.PriceSalesRatio,
			&oFRA.DividendYield,
			&oFRA.EnterpriseValueMultiple,
			&oFRA.PriceFairValue)
		oListFRA = append(oListFRA, oFRA)
	}

	//OK
	return oListFRA, nil
}

func Si_Find_Quarter(symbol string, limit int) ([]models.FinancialRatio_Quarter, error) {

	db := models.SingleStoreCN
	q := `SELECT date,
    symbol,
    period,
    currentRatio,
    quickRatio,
    cashRatio,
    daysOfSalesOutstanding,
    daysOfInventoryOutstanding,
    operatingCycle,
    daysOfPayablesOutstanding,
    cashConversionCycle,
    grossProfitMargin,
    operatingProfitMargin,
    pretaxProfitMargin,
    netProfitMargin,
    effectiveTaxRate,
    returnOnAssets,
    returnOnEquity,
    returnOnCapitalEmployed,
    netIncomePerEBT,
    ebtPerEbit,
    ebitPerRevenue,
    debtRatio,
    debtEquityRatio,
    longTermDebtToCapitalization,
    totalDebtToCapitalization,
    interestCoverage,
    cashFlowToDebtRatio,
    companyEquityMultiplier,
    receivablesTurnover,
    payablesTurnover,
    inventoryTurnover,
    fixedAssetTurnover,
    assetTurnover,
    operatingCashFlowPerShare,
    freeCashFlowPerShare,
    cashPerShare,
    payoutRatio,
    operatingCashFlowSalesRatio,
    freeCashFlowOperatingCashFlowRatio,
    cashFlowCoverageRatios,
    shortTermCoverageRatios,
    capitalExpenditureCoverageRatio,
    dividendPaidAndCapexCoverageRatio,
    dividendPayoutRatio,
    priceBookValueRatio,
    priceToBookRatio,
    priceEarningsRatio,
    priceToFreeCashFlowsRatio,
    priceToOperatingCashFlowsRatio,
    priceCashFlowRatio,
    priceEarningsToGrowthRatio,
    priceSalesRatio,
    dividendYield,
    enterpriseValueMultiple,
    priceFairValue FROM FinancialRatio_Quarter WHERE symbol = ? LIMIT ` + strconv.Itoa(limit)
	rows, error_show := db.Query(q, symbol, limit)

	oListFRQ := []models.FinancialRatio_Quarter{}

	if error_show != nil {

		return oListFRQ, error_show
	}

	for rows.Next() {
		oFRQ := models.FinancialRatio_Quarter{}
		rows.Scan(&oFRQ.Date,
			&oFRQ.Symbol,
			&oFRQ.Period,
			&oFRQ.CurrentRatio,
			&oFRQ.QuickRatio,
			&oFRQ.CashRatio,
			&oFRQ.DaysOfSalesOutstanding,
			&oFRQ.DaysOfInventoryOutstanding,
			&oFRQ.OperatingCycle,
			&oFRQ.DaysOfPayablesOutstanding,
			&oFRQ.CashConversionCycle,
			&oFRQ.GrossProfitMargin,
			&oFRQ.OperatingProfitMargin,
			&oFRQ.PretaxProfitMargin,
			&oFRQ.NetProfitMargin,
			&oFRQ.EffectiveTaxRate,
			&oFRQ.ReturnOnAssets,
			&oFRQ.ReturnOnEquity,
			&oFRQ.ReturnOnCapitalEmployed,
			&oFRQ.NetIncomePerEBT,
			&oFRQ.EbtPerEbit,
			&oFRQ.EbitPerRevenue,
			&oFRQ.DebtRatio,
			&oFRQ.DebtEquityRatio,
			&oFRQ.LongTermDebtToCapitalization,
			&oFRQ.TotalDebtToCapitalization,
			&oFRQ.InterestCoverage,
			&oFRQ.CashFlowToDebtRatio,
			&oFRQ.CompanyEquityMultiplier,
			&oFRQ.ReceivablesTurnover,
			&oFRQ.PayablesTurnover,
			&oFRQ.InventoryTurnover,
			&oFRQ.FixedAssetTurnover,
			&oFRQ.AssetTurnover,
			&oFRQ.OperatingCashFlowPerShare,
			&oFRQ.FreeCashFlowPerShare,
			&oFRQ.CashPerShare,
			&oFRQ.PayoutRatio,
			&oFRQ.OperatingCashFlowSalesRatio,
			&oFRQ.FreeCashFlowOperatingCashFlowRatio,
			&oFRQ.CashFlowCoverageRatios,
			&oFRQ.ShortTermCoverageRatios,
			&oFRQ.CapitalExpenditureCoverageRatio,
			&oFRQ.DividendPaidAndCapexCoverageRatio,
			&oFRQ.DividendPayoutRatio,
			&oFRQ.PriceBookValueRatio,
			&oFRQ.PriceToBookRatio,
			&oFRQ.PriceEarningsRatio,
			&oFRQ.PriceToFreeCashFlowsRatio,
			&oFRQ.PriceToOperatingCashFlowsRatio,
			&oFRQ.PriceCashFlowRatio,
			&oFRQ.PriceEarningsToGrowthRatio,
			&oFRQ.PriceSalesRatio,
			&oFRQ.DividendYield,
			&oFRQ.EnterpriseValueMultiple,
			&oFRQ.PriceFairValue)
		oListFRQ = append(oListFRQ, oFRQ)
	}

	//OK
	return oListFRQ, nil
}

func Si_Find_AnnualTTM(symbol string, limit int) ([]models.FinancialRatio_AnnualTTM, error) {

	db := models.SingleStoreCN
	q := `SELECT symbol,
    dividendYielTTM,
    dividendYielPercentageTTM,
    peRatioTTM,
    pegRatioTTM,
    payoutRatioTTM,
    currentRatioTTM,
    quickRatioTTM,
    cashRatioTTM,
    daysOfSalesOutstandingTTM,
    daysOfInventoryOutstandingTTM,
    operatingCycleTTM,
    daysOfPayablesOutstandingTTM,
    cashConversionCycleTTM,
    grossProfitMarginTTM,
    operatingProfitMarginTTM,
    pretaxProfitMarginTTM,
    netProfitMarginTTM,
    effectiveTaxRateTTM,
    returnOnAssetsTTM,
    returnOnEquityTTM,
    returnOnCapitalEmployedTTM,
    netIncomePerEBTTTM,
    ebtPerEbitTTM,
    ebitPerRevenueTTM,
    debtRatioTTM,
    debtEquityRatioTTM,
    longTermDebtToCapitalizationTTM,
    totalDebtToCapitalizationTTM,
    interestCoverageTTM,
    cashFlowToDebtRatioTTM,
    companyEquityMultiplierTTM,
    receivablesTurnoverTTM,
    payablesTurnoverTTM,
    inventoryTurnoverTTM,
    fixedAssetTurnoverTTM,
    assetTurnoverTTM,
    operatingCashFlowPerShareTTM,
    freeCashFlowPerShareTTM,
    cashPerShareTTM,
    operatingCashFlowSalesRatioTTM,
    freeCashFlowOperatingCashFlowRatioTTM,
    cashFlowCoverageRatiosTTM,
    shortTermCoverageRatiosTTM,
    capitalExpenditureCoverageRatioTTM,
    dividendPaidAndCapexCoverageRatioTTM,
    priceBookValueRatioTTM,
    priceToBookRatioTTM,
    priceToSalesRatioTTM,
    priceEarningsRatioTTM,
    priceToFreeCashFlowsRatioTTM,
    priceToOperatingCashFlowsRatioTTM,
    priceCashFlowRatioTTM,
    priceEarningsToGrowthRatioTTM,
    priceSalesRatioTTM,
    dividendYieldTTM,
    enterpriseValueMultipleTTM,
    priceFairValueTTM,
    dividendPerShareTTM FROM FinancialRatio_AnnualTTM WHERE symbol = ? LIMIT ` + strconv.Itoa(limit)
	rows, error_show := db.Query(q, symbol)

	oListFRATTM := []models.FinancialRatio_AnnualTTM{}

	if error_show != nil {

		return oListFRATTM, error_show
	}

	for rows.Next() {
		oFRATTM := models.FinancialRatio_AnnualTTM{}
		rows.Scan(&oFRATTM.Symbol,
			&oFRATTM.DividendYielTTM,
			&oFRATTM.DividendYielPercentageTTM,
			&oFRATTM.PeRatioTTM,
			&oFRATTM.PegRatioTTM,
			&oFRATTM.PayoutRatioTTM,
			&oFRATTM.CurrentRatioTTM,
			&oFRATTM.QuickRatioTTM,
			&oFRATTM.CashRatioTTM,
			&oFRATTM.DaysOfSalesOutstandingTTM,
			&oFRATTM.DaysOfInventoryOutstandingTTM,
			&oFRATTM.OperatingCycleTTM,
			&oFRATTM.DaysOfPayablesOutstandingTTM,
			&oFRATTM.CashConversionCycleTTM,
			&oFRATTM.GrossProfitMarginTTM,
			&oFRATTM.OperatingProfitMarginTTM,
			&oFRATTM.PretaxProfitMarginTTM,
			&oFRATTM.NetProfitMarginTTM,
			&oFRATTM.EffectiveTaxRateTTM,
			&oFRATTM.ReturnOnAssetsTTM,
			&oFRATTM.ReturnOnEquityTTM,
			&oFRATTM.ReturnOnCapitalEmployedTTM,
			&oFRATTM.NetIncomePerEBTTTM,
			&oFRATTM.EbtPerEbitTTM,
			&oFRATTM.EbitPerRevenueTTM,
			&oFRATTM.DebtRatioTTM,
			&oFRATTM.DebtEquityRatioTTM,
			&oFRATTM.LongTermDebtToCapitalizationTTM,
			&oFRATTM.TotalDebtToCapitalizationTTM,
			&oFRATTM.InterestCoverageTTM,
			&oFRATTM.CashFlowToDebtRatioTTM,
			&oFRATTM.CompanyEquityMultiplierTTM,
			&oFRATTM.ReceivablesTurnoverTTM,
			&oFRATTM.PayablesTurnoverTTM,
			&oFRATTM.InventoryTurnoverTTM,
			&oFRATTM.FixedAssetTurnoverTTM,
			&oFRATTM.AssetTurnoverTTM,
			&oFRATTM.OperatingCashFlowPerShareTTM,
			&oFRATTM.FreeCashFlowPerShareTTM,
			&oFRATTM.CashPerShareTTM,
			&oFRATTM.OperatingCashFlowSalesRatioTTM,
			&oFRATTM.FreeCashFlowOperatingCashFlowRatioTTM,
			&oFRATTM.CashFlowCoverageRatiosTTM,
			&oFRATTM.ShortTermCoverageRatiosTTM,
			&oFRATTM.CapitalExpenditureCoverageRatioTTM,
			&oFRATTM.DividendPaidAndCapexCoverageRatioTTM,
			&oFRATTM.PriceBookValueRatioTTM,
			&oFRATTM.PriceToBookRatioTTM,
			&oFRATTM.PriceToSalesRatioTTM,
			&oFRATTM.PriceEarningsRatioTTM,
			&oFRATTM.PriceToFreeCashFlowsRatioTTM,
			&oFRATTM.PriceToOperatingCashFlowsRatioTTM,
			&oFRATTM.PriceCashFlowRatioTTM,
			&oFRATTM.PriceEarningsToGrowthRatioTTM,
			&oFRATTM.PriceSalesRatioTTM,
			&oFRATTM.DividendYieldTTM,
			&oFRATTM.EnterpriseValueMultipleTTM,
			&oFRATTM.PriceFairValueTTM,
			&oFRATTM.DividendPerShareTTM)
		oListFRATTM = append(oListFRATTM, oFRATTM)
	}

	//OK
	return oListFRATTM, nil
}
